const dummyData = [
  {
    id: 1,
    type: "veg",
    size: "large",
    base: "thin",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 2,
    type: "non-veg",
    size: "medium",
    base: "thick",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 3,
    type: "veg",
    size: "small",
    base: "thin",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 4,
    type: "veg",
    size: "large",
    base: "thick",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 5,
    type: "non-veg",
    size: "medium",
    base: "thin",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 6,
    type: "veg",
    size: "small",
    base: "thick",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 7,
    type: "veg",
    size: "large",
    base: "thin",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 8,
    type: "non-veg",
    size: "medium",
    base: "thick",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 9,
    type: "veg",
    size: "small",
    base: "thin",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
  {
    id: 10,
    type: "veg",
    size: "large",
    base: "thick",
    stage: "Order Placed",
    totalTimeSpent: 0,
  },
];

export default dummyData;
